<?php

namespace ContainerJKQxxex;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NG61dgqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nG61dgq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nG61dgq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LeaveManagementController::enAttente' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::index' => ['privates', '.service_locator.9.EA2Tq', 'get_ServiceLocator_9_EA2TqService', true],
            'App\\Controller\\LeaveManagementController::refus' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::suppression' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::validation' => ['privates', '.service_locator.BF135X0', 'get_ServiceLocator_BF135X0Service', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.GMs5F5S', 'get_ServiceLocator_GMs5F5SService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StaffVacationController::delete' => ['privates', '.service_locator.rMV3m6Z', 'get_ServiceLocator_RMV3m6ZService', true],
            'App\\Controller\\StaffVacationController::index' => ['privates', '.service_locator.ZVQqiHX', 'get_ServiceLocator_ZVQqiHXService', true],
            'App\\Controller\\StaffVacationController::modify' => ['privates', '.service_locator.kaxaMdc', 'get_ServiceLocator_KaxaMdcService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.itpeuSf', 'get_ServiceLocator_ItpeuSfService', true],
            'App\\Controller\\UserController::detail' => ['privates', '.service_locator.CElJlu_', 'get_ServiceLocator_CElJluService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.eRJx6vO', 'get_ServiceLocator_ERJx6vOService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.CElJlu_', 'get_ServiceLocator_CElJluService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.GMs5F5S', 'get_ServiceLocator_GMs5F5SService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LeaveManagementController:enAttente' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:index' => ['privates', '.service_locator.9.EA2Tq', 'get_ServiceLocator_9_EA2TqService', true],
            'App\\Controller\\LeaveManagementController:refus' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:suppression' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:validation' => ['privates', '.service_locator.BF135X0', 'get_ServiceLocator_BF135X0Service', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.GMs5F5S', 'get_ServiceLocator_GMs5F5SService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StaffVacationController:delete' => ['privates', '.service_locator.rMV3m6Z', 'get_ServiceLocator_RMV3m6ZService', true],
            'App\\Controller\\StaffVacationController:index' => ['privates', '.service_locator.ZVQqiHX', 'get_ServiceLocator_ZVQqiHXService', true],
            'App\\Controller\\StaffVacationController:modify' => ['privates', '.service_locator.kaxaMdc', 'get_ServiceLocator_KaxaMdcService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.itpeuSf', 'get_ServiceLocator_ItpeuSfService', true],
            'App\\Controller\\UserController:detail' => ['privates', '.service_locator.CElJlu_', 'get_ServiceLocator_CElJluService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.eRJx6vO', 'get_ServiceLocator_ERJx6vOService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.CElJlu_', 'get_ServiceLocator_CElJluService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.GMs5F5S', 'get_ServiceLocator_GMs5F5SService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LeaveManagementController::enAttente' => '?',
            'App\\Controller\\LeaveManagementController::index' => '?',
            'App\\Controller\\LeaveManagementController::refus' => '?',
            'App\\Controller\\LeaveManagementController::suppression' => '?',
            'App\\Controller\\LeaveManagementController::validation' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StaffVacationController::delete' => '?',
            'App\\Controller\\StaffVacationController::index' => '?',
            'App\\Controller\\StaffVacationController::modify' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::detail' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LeaveManagementController:enAttente' => '?',
            'App\\Controller\\LeaveManagementController:index' => '?',
            'App\\Controller\\LeaveManagementController:refus' => '?',
            'App\\Controller\\LeaveManagementController:suppression' => '?',
            'App\\Controller\\LeaveManagementController:validation' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StaffVacationController:delete' => '?',
            'App\\Controller\\StaffVacationController:index' => '?',
            'App\\Controller\\StaffVacationController:modify' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:detail' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
