vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    user_image:
      uri_prefix: "/assets/Img/profile_picture"
      upload_destination: "%kernel.project_dir%/public/assets/Img/profile_picture"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    company_logo_image:
      uri_prefix: "/assets/Img/company_logo"
      upload_destination: "%kernel.project_dir%/public/assets/Img/company_logo"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
    signature_image:
      uri_prefix: "/assets/Img/signature"
      upload_destination: "%kernel.project_dir%/public/assets/Img/signature"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
