<?php

namespace ContainerGyEjXBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XwGYWxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xwG_YWx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xwG_YWx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'company' => ['privates', '.errored..service_locator.xwG_YWx.App\\Entity\\Company', NULL, 'Cannot autowire service ".service_locator.xwG_YWx": it needs an instance of "App\\Entity\\Company" but this type has been excluded in "config/services.yaml".'],
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'user' => ['privates', '.errored..service_locator.xwG_YWx.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.xwG_YWx": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'company' => 'App\\Entity\\Company',
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'manager' => '?',
            'security' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
