<?php

namespace ContainerGyEjXBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JRWZqsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J_rWZqs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J_rWZqs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyRepository' => ['privates', 'App\\Repository\\CompanyRepository', 'getCompanyRepositoryService', true],
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'numberDayOffRepository' => ['privates', 'App\\Repository\\NumberDayOffRepository', 'getNumberDayOffRepositoryService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'vacationRepository' => ['privates', 'App\\Repository\\VacationRepository', 'getVacationRepositoryService', true],
        ], [
            'companyRepository' => 'App\\Repository\\CompanyRepository',
            'manager' => '?',
            'numberDayOffRepository' => 'App\\Repository\\NumberDayOffRepository',
            'security' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'vacationRepository' => 'App\\Repository\\VacationRepository',
        ]);
    }
}
