<?php

namespace ContainerGyEjXBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ItsoJoPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.itsoJoP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.itsoJoP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CompanyProfileController::editCompany' => ['privates', '.service_locator.xwG_YWx', 'get_ServiceLocator_XwGYWxService', true],
            'App\\Controller\\CompanyProfileController::newAdmin' => ['privates', '.service_locator.a_nr8Tn', 'get_ServiceLocator_ANr8TnService', true],
            'App\\Controller\\CompanyProfileController::newCompany' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\LeaveManagementController::enAttente' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::generateDocument' => ['privates', '.service_locator.fFD37lL', 'get_ServiceLocator_FFD37lLService', true],
            'App\\Controller\\LeaveManagementController::index' => ['privates', '.service_locator.Ul_Qvgk', 'get_ServiceLocator_UlQvgkService', true],
            'App\\Controller\\LeaveManagementController::refus' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::suppression' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController::validation' => ['privates', '.service_locator.BF135X0', 'get_ServiceLocator_BF135X0Service', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.9Z0XlHk', 'get_ServiceLocator_9Z0XlHkService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StaffVacationController::delete' => ['privates', '.service_locator.rMV3m6Z', 'get_ServiceLocator_RMV3m6ZService', true],
            'App\\Controller\\StaffVacationController::index' => ['privates', '.service_locator.J_rWZqs', 'get_ServiceLocator_JRWZqsService', true],
            'App\\Controller\\StaffVacationController::modify' => ['privates', '.service_locator.SHBjyoO', 'get_ServiceLocator_SHBjyoOService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.itpeuSf', 'get_ServiceLocator_ItpeuSfService', true],
            'App\\Controller\\UserController::detail' => ['privates', '.service_locator.MO423Cu', 'get_ServiceLocator_MO423CuService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.2koa9ic', 'get_ServiceLocator_2koa9icService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.MO423Cu', 'get_ServiceLocator_MO423CuService', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.9Z0XlHk', 'get_ServiceLocator_9Z0XlHkService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CompanyProfileController:editCompany' => ['privates', '.service_locator.xwG_YWx', 'get_ServiceLocator_XwGYWxService', true],
            'App\\Controller\\CompanyProfileController:newAdmin' => ['privates', '.service_locator.a_nr8Tn', 'get_ServiceLocator_ANr8TnService', true],
            'App\\Controller\\CompanyProfileController:newCompany' => ['privates', '.service_locator.V71r_w4', 'get_ServiceLocator_V71rW4Service', true],
            'App\\Controller\\LeaveManagementController:enAttente' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:generateDocument' => ['privates', '.service_locator.fFD37lL', 'get_ServiceLocator_FFD37lLService', true],
            'App\\Controller\\LeaveManagementController:index' => ['privates', '.service_locator.Ul_Qvgk', 'get_ServiceLocator_UlQvgkService', true],
            'App\\Controller\\LeaveManagementController:refus' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:suppression' => ['privates', '.service_locator.gTFsReg', 'get_ServiceLocator_GTFsRegService', true],
            'App\\Controller\\LeaveManagementController:validation' => ['privates', '.service_locator.BF135X0', 'get_ServiceLocator_BF135X0Service', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.9Z0XlHk', 'get_ServiceLocator_9Z0XlHkService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\StaffVacationController:delete' => ['privates', '.service_locator.rMV3m6Z', 'get_ServiceLocator_RMV3m6ZService', true],
            'App\\Controller\\StaffVacationController:index' => ['privates', '.service_locator.J_rWZqs', 'get_ServiceLocator_JRWZqsService', true],
            'App\\Controller\\StaffVacationController:modify' => ['privates', '.service_locator.SHBjyoO', 'get_ServiceLocator_SHBjyoOService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.itpeuSf', 'get_ServiceLocator_ItpeuSfService', true],
            'App\\Controller\\UserController:detail' => ['privates', '.service_locator.MO423Cu', 'get_ServiceLocator_MO423CuService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.2koa9ic', 'get_ServiceLocator_2koa9icService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.MO423Cu', 'get_ServiceLocator_MO423CuService', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.9Z0XlHk', 'get_ServiceLocator_9Z0XlHkService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CompanyProfileController::editCompany' => '?',
            'App\\Controller\\CompanyProfileController::newAdmin' => '?',
            'App\\Controller\\CompanyProfileController::newCompany' => '?',
            'App\\Controller\\LeaveManagementController::enAttente' => '?',
            'App\\Controller\\LeaveManagementController::generateDocument' => '?',
            'App\\Controller\\LeaveManagementController::index' => '?',
            'App\\Controller\\LeaveManagementController::refus' => '?',
            'App\\Controller\\LeaveManagementController::suppression' => '?',
            'App\\Controller\\LeaveManagementController::validation' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\StaffVacationController::delete' => '?',
            'App\\Controller\\StaffVacationController::index' => '?',
            'App\\Controller\\StaffVacationController::modify' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::detail' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CompanyProfileController:editCompany' => '?',
            'App\\Controller\\CompanyProfileController:newAdmin' => '?',
            'App\\Controller\\CompanyProfileController:newCompany' => '?',
            'App\\Controller\\LeaveManagementController:enAttente' => '?',
            'App\\Controller\\LeaveManagementController:generateDocument' => '?',
            'App\\Controller\\LeaveManagementController:index' => '?',
            'App\\Controller\\LeaveManagementController:refus' => '?',
            'App\\Controller\\LeaveManagementController:suppression' => '?',
            'App\\Controller\\LeaveManagementController:validation' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\StaffVacationController:delete' => '?',
            'App\\Controller\\StaffVacationController:index' => '?',
            'App\\Controller\\StaffVacationController:modify' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:detail' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
