<?php

namespace ContainerGyEjXBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RMV3m6ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rMV3m6Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rMV3m6Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'numberDayOffRepository' => ['privates', 'App\\Repository\\NumberDayOffRepository', 'getNumberDayOffRepositoryService', true],
            'vacation' => ['privates', '.errored..service_locator.rMV3m6Z.App\\Entity\\Vacation', NULL, 'Cannot autowire service ".service_locator.rMV3m6Z": it needs an instance of "App\\Entity\\Vacation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'manager' => '?',
            'numberDayOffRepository' => 'App\\Repository\\NumberDayOffRepository',
            'vacation' => 'App\\Entity\\Vacation',
        ]);
    }
}
