<?php

namespace ContainerGyEjXBL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVacation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rMV3m6Z.App\Entity\Vacation' shared service.
     *
     * @return \App\Entity\Vacation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rMV3m6Z": it needs an instance of "App\\Entity\\Vacation" but this type has been excluded in "config/services.yaml".');
    }
}
