<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgQ7Osa\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgQ7Osa/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQgQ7Osa.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQgQ7Osa\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQgQ7Osa\App_KernelProdContainer([
    'container.build_hash' => 'QgQ7Osa',
    'container.build_id' => 'bc35ebde',
    'container.build_time' => 1705404425,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgQ7Osa');
