<?php

namespace ContainerQgQ7Osa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumberDayOffRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\NumberDayOffRepository' shared autowired service.
     *
     * @return \App\Repository\NumberDayOffRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NumberDayOffRepository'] = new \App\Repository\NumberDayOffRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
