<?php

namespace ContainerQgQ7Osa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVacationHoursTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\VacationHoursType' shared autowired service.
     *
     * @return \App\Form\VacationHoursType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\VacationHoursType'] = new \App\Form\VacationHoursType();
    }
}
