<?php

namespace ContainerQgQ7Osa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVacationRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VacationRepository' shared autowired service.
     *
     * @return \App\Repository\VacationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VacationRepository'] = new \App\Repository\VacationRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
