# config/app_config.yaml

parameters:
  company_creat: "AMerguin"
  company_name: "Mairie de Deyvillers"
  company_city: "Deyvillers"
  company_address: "2 Rue de Lorraine"
  company_zipcode: "88000"
  company_phone: "0329340870"
  company_email: "contact@deyvillers.fr"
  company_abrev: "Deyvi"
  company_blazon: "changer public/assets/svg/blason.svg"
  company_paysage: "changer public/assets/Img/img_hero.jpg"
