<?php

namespace ContainerR435Cw0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BF135X0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BF135X0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BF135X0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'numberDayOffRepository' => ['privates', 'App\\Repository\\NumberDayOffRepository', 'getNumberDayOffRepositoryService', true],
            'vacationRepository' => ['privates', 'App\\Repository\\VacationRepository', 'getVacationRepositoryService', true],
        ], [
            'manager' => '?',
            'numberDayOffRepository' => 'App\\Repository\\NumberDayOffRepository',
            'vacationRepository' => 'App\\Repository\\VacationRepository',
        ]);
    }
}
