<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR435Cw0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR435Cw0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR435Cw0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR435Cw0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR435Cw0\App_KernelDevDebugContainer([
    'container.build_hash' => 'R435Cw0',
    'container.build_id' => 'd32e13aa',
    'container.build_time' => 1705408330,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR435Cw0');
