<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGyEjXBL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGyEjXBL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGyEjXBL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGyEjXBL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGyEjXBL\App_KernelDevDebugContainer([
    'container.build_hash' => 'GyEjXBL',
    'container.build_id' => '25626907',
    'container.build_time' => 1706527772,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGyEjXBL');
