<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE42jVmx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE42jVmx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE42jVmx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE42jVmx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE42jVmx\App_KernelDevDebugContainer([
    'container.build_hash' => 'E42jVmx',
    'container.build_id' => 'dde50d23',
    'container.build_time' => 1704469869,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE42jVmx');
