<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NumberDayOff extends \App\Entity\NumberDayOff implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'available' => [parent::class, 'available', null],
        "\0".parent::class."\0".'cet' => [parent::class, 'cet', null],
        "\0".parent::class."\0".'hoursAvailable' => [parent::class, 'hoursAvailable', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'userDay' => [parent::class, 'userDay', null],
        'available' => [parent::class, 'available', null],
        'cet' => [parent::class, 'cet', null],
        'hoursAvailable' => [parent::class, 'hoursAvailable', null],
        'id' => [parent::class, 'id', null],
        'userDay' => [parent::class, 'userDay', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
