<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adress' => [parent::class, 'adress', null],
        "\0".parent::class."\0".'birthday' => [parent::class, 'birthday', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'job' => [parent::class, 'job', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'profilePictureFile' => [parent::class, 'profilePictureFile', null],
        "\0".parent::class."\0".'profilePictureName' => [parent::class, 'profilePictureName', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'socialSecurity' => [parent::class, 'socialSecurity', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'vacations' => [parent::class, 'vacations', null],
        "\0".parent::class."\0".'zipcode' => [parent::class, 'zipcode', null],
        'adress' => [parent::class, 'adress', null],
        'birthday' => [parent::class, 'birthday', null],
        'city' => [parent::class, 'city', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'job' => [parent::class, 'job', null],
        'lastname' => [parent::class, 'lastname', null],
        'password' => [parent::class, 'password', null],
        'phone' => [parent::class, 'phone', null],
        'profilePictureFile' => [parent::class, 'profilePictureFile', null],
        'profilePictureName' => [parent::class, 'profilePictureName', null],
        'roles' => [parent::class, 'roles', null],
        'socialSecurity' => [parent::class, 'socialSecurity', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'vacations' => [parent::class, 'vacations', null],
        'zipcode' => [parent::class, 'zipcode', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
